openapi: 3.0.0
info:
    description: kafka-lag-stats API documentation
    version: 1.0.0
    title: kafka_lag_stats
servers:
    - url: http://localhost:8080/api
      description: Development server
    - url: https://localhost:8080/api
      description: Development server with TLS Profile
tags:
    - name: kafka-lag-stats
      description: Kafka Lag Stats
security:
    - jwt: []
    - basic: []

paths:
    /kafka-lag/lags:
        get:
            tags:
                - kafka-lag-stats
            summary: get the last lags in time for a single consumer
            operationId: getLags
            parameters:
                - name: group
                  in: query
                  description: the consumer group of the consumer
                  required: true
                  schema:
                      type: string
                - name: key
                  in: query
                  description: the partition key used to get the partition of the consumer  (give partition or key but not both)
                  required: false
                  schema:
                      type: string
                - name: partition
                  in: query
                  description: the partition of the consumer (provide partition or key but not both)
                  required: false
                  schema:
                      type: integer
                      format: int32
                - name: topic
                  in: query
                  description: the topic subscribed by the consumer
                  required: true
                  schema:
                      type: string
            responses:
                "200":
                    description: the last lags of the consumer
                    content:
                        "application/json":
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/MessageLag"
                "default":
                    $ref: "#/components/responses/Problem"

    /kafka-lag/messages-remaining:
        get:
            tags:
                - kafka-lag-stats
            summary: get the number of messages that a consumer still has to consume to reach a message published at a given time
            operationId: getMessagesToPublishTimestamp
            parameters:
                - name: group
                  in: query
                  description: the consumer group of the consumer
                  required: true
                  schema:
                      type: string
                - name: key
                  in: query
                  description: the partition key used to get the partition of the consumer  (give partition or key but not both)
                  required: false
                  schema:
                      type: string
                - name: partition
                  in: query
                  description: the partition  of the consumer (provide partition or key but not both)
                  required: false
                  schema:
                      type: integer
                      format: int32
                - name: publishTimestamp
                  in: query
                  description: the timestamp at which the message was published
                  required: false
                  schema:
                      type: string
                - name: topic
                  in: query
                  description: the topic subscribed by the consumer
                  required: true
                  schema:
                      type: string
            responses:
                "200":
                    description: the number of messages that still have to be consumed
                    content:
                        "application/json":
                            schema:
                                $ref: "#/components/schemas/MessageLag"
                "default":
                    $ref: "#/components/responses/Problem"

    /kafka-lag/partition:
        get:
            tags:
                - kafka-lag-stats
            summary: get the partition for the given topic and key
            operationId: getPartition
            parameters:
                - name: key
                  in: query
                  description: the key
                  required: true
                  schema:
                      type: string
                - name: topic
                  in: query
                  description: the topic
                  required: true
                  schema:
                      type: string
            responses:
                "200":
                    description: the partition number
                    content:
                        "application/json":
                            schema:
                                type: integer
                                format: int32
                "default":
                    $ref: "#/components/responses/Problem"

    /kafka-lag/speed-stats:
        get:
            tags:
                - kafka-lag-stats
            summary: get the average consumption speed of a given consumer
            operationId: getSpeedStats
            parameters:
                - name: group
                  in: query
                  description: the consumer group of the consumer
                  required: true
                  schema:
                      type: string
                - name: key
                  in: query
                  description: the partition key used to get the partition of the consumer  (give partition or key but not both)
                  required: false
                  schema:
                      type: string
                - name: partition
                  in: query
                  description: the partition  of the consumer (provide partition or key but not both)
                  required: false
                  schema:
                      type: integer
                      format: int32
                - name: topic
                  in: query
                  description: the topic subscribed by the consumer
                  required: true
                  schema:
                      type: string
            responses:
                "200":
                    description: the average speed of the consumer
                    content:
                        "application/json":
                            schema:
                                $ref: "#/components/schemas/SpeedStats"
                "default":
                    $ref: "#/components/responses/Problem"

    /kafka-lag/speeds:
        get:
            tags:
                - kafka-lag-stats
            summary: get the last consumption speeds in time for a single consumer
            operationId: getSpeeds
            parameters:
                - name: group
                  in: query
                  description: the consumer group of the consumer
                  required: true
                  schema:
                      type: string
                - name: key
                  in: query
                  description: the partition key used to get the partition of the consumer  (give partition or key but not both)
                  required: false
                  schema:
                      type: string
                - name: partition
                  in: query
                  description: the partition  of the consumer (provide partition or key but not both)
                  required: false
                  schema:
                      type: integer
                      format: int32
                - name: topic
                  in: query
                  description: the topic subscribed by the consumer
                  required: true
                  schema:
                      type: string
            responses:
                "200":
                    description: the last consumption speeds of the consumer
                    content:
                        "application/json":
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/MessageSpeed"
                "default":
                    $ref: "#/components/responses/Problem"

    /kafka-lag/time-remaining:
        get:
            tags:
                - kafka-lag-stats
            summary: get the time that a consumer still needs to consume a message published at a given time
            operationId: getTimeRemaining
            parameters:
                - name: group
                  in: query
                  description: the consumer group of the consumer
                  required: true
                  schema:
                      type: string
                - name: key
                  in: query
                  description: the partition key used to get the partition of the consumer  (give partition or key but not both)
                  required: false
                  schema:
                      type: string
                - name: partition
                  in: query
                  description: the partition  of the consumer (provide partition or key but not both)
                  required: false
                  schema:
                      type: integer
                      format: int32
                - name: publishTimestamp
                  in: query
                  description: the timestamp at which the message was published
                  required: false
                  schema:
                      type: string
                - name: topic
                  in: query
                  description: the topic subscribed by the consumer
                  required: true
                  schema:
                      type: string
            responses:
                "200":
                    description: the time that the consumer still needs to consume the message
                    content:
                        "application/json":
                            schema:
                                $ref: "#/components/schemas/TimeRemaining"
                "default":
                    $ref: "#/components/responses/Problem"

    /kafka-lag/time-remaining-stats:
        get:
            tags:
                - kafka-lag-stats
            summary: get the average time that a consumer still needs to consume a message published
            operationId: getTimeRemainingStats
            parameters:
                - name: group
                  in: query
                  description: the consumer group of the consumer
                  required: true
                  schema:
                      type: string
                - name: publishTimestamp
                  in: query
                  description: the timestamp at which the message was published
                  required: false
                  schema:
                      type: string
                - name: topic
                  in: query
                  description: the topic subscribed by the consumer
                  required: true
                  schema:
                      type: string
            responses:
                "200":
                    description: the time that the consumer still needs to consume the message
                    content:
                        "application/json":
                            schema:
                                $ref: "#/components/schemas/TimeRemainingStats"
                "default":
                    $ref: "#/components/responses/Problem"

components:
    securitySchemes:
        jwt:
            type: http
            description: JWT Authentication
            scheme: bearer
            bearerFormat: JWT
        basic:
            type: http
            description: Basic Authentication
            scheme: basic
    responses:
        Problem:
            description: error occurred - see status code and problem object for more information.
            content:
                "application/problem+json":
                    schema:
                        $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
    schemas:
        DoubleStats:
            type: object
            properties:
                mean:
                    type: number
                    format: double
                stddev:
                    type: number
                    format: double
                stddevPercent:
                    type: number
                    format: double
            title: DoubleStats
        MessageLag:
            type: object
            properties:
                consumerOffset:
                    type: integer
                    format: int64
                lagMessages:
                    type: integer
                    format: int64
                producerOffset:
                    type: integer
                    format: int64
                timestamp:
                    type: string
                    format: date-time
            title: MessageLag
        MessageSpeed:
            type: object
            properties:
                lag:
                    $ref: "#/components/schemas/MessageLag"
                speed:
                    type: number
                    format: double
                timestamp:
                    type: string
                    format: date-time
            title: MessageSpeed
        SpeedStats:
            type: object
            properties:
                meanSpeed:
                    $ref: "#/components/schemas/DoubleStats"
                speeds:
                    type: array
                    items:
                        $ref: "#/components/schemas/MessageSpeed"
            title: SpeedStats
        TimeRemaining:
            type: object
            properties:
                messageLag:
                    $ref: "#/components/schemas/MessageLag"
                partition:
                    type: integer
                    format: int32
                speedStats:
                    $ref: "#/components/schemas/SpeedStats"
                timeRemaining:
                    type: number
                    format: double
            title: TimeRemaining
        TimeRemainingStats:
            type: object
            properties:
                meanTimeOverPartitions:
                    $ref: "#/components/schemas/DoubleStats"
                partitionTimesRemaining:
                    type: object
                    additionalProperties:
                        $ref: "#/components/schemas/TimeRemaining"
            title: TimeRemainingStats
